name: LeetCode Sync

on:
  workflow_dispatch:

  schedule:
    # Runs every day at 6:00 PM IST
    # GitHub cron uses UTC, so 18:00 IST = 12:30 UTC
    - cron: "30 12 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          filter-duplicate-secs: 86400
          verbose: true
          commit-header: "[LeetCode Sync]"